version: "3.6"

services:
    nginx:
        image: easybar/nginx:dev
        depends_on:
            - app
        environment:
            - DOCROOT=/srv/public
        volumes:
            - .:/srv
    app:
        image: easybar/php:7.2.9-dev
        depends_on:
            - db
        volumes:
            - .:/srv

    db:
        image: mariadb:10.2.10
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: paris
        volumes:
            - db-data:/var/lib/mysql
    adminer:
        image: adminer
        ports:
            - '8083:8080'
        environment:
            - ADMINER_DEFAULT_SERVER=db
            - ADMINER_DESIGN=brade
volumes:
    db-data: {}
